### ISSUE TITLE
Game crash when placing any other item (besides weapon/tool/armor) on the composing block

### ISSUE THREAD

**Issue by varencilator** [fabric-community/Composing#5]
Tried a lever, then a stick, then a glass block:
[crash-2021-04-26_18.07.26-server.txt](https://github.com/fabric-community/Composing/files/6380641/crash-2021-04-26_18.07.26-server.txt)
[crash-2021-04-26_18.10.06-server.txt](https://github.com/fabric-community/Composing/files/6380642/crash-2021-04-26_18.10.06-server.txt)
[crash-2021-04-26_18.06.06-server.txt](https://github.com/fabric-community/Composing/files/6380643/crash-2021-04-26_18.06.06-server.txt)

**Comment by Martmists-GH** [comment]
Install Trinkets

**Comment by varencilator** [comment]
Thanks, thanks, I'm dumb
